address comments

diff --git a/.github/workflows/trigger-mainfork-snapshot.yaml b/.github/workflows/trigger-mainfork-snapshot.yaml
--- a/.github/workflows/trigger-mainfork-snapshot.yaml
+++ b/.github/workflows/trigger-mainfork-snapshot.yaml
@@ -9,7 +9,6 @@ jobs:
     permissions:
       contents: read
       id-token: write
-      packages: write
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
@@ -59,19 +58,19 @@ jobs:
 
           FOLLOWER_HOMEPAGE="https://followmain.agoric.net"
 
-          IMAGE_TAG="$(
-            curl --silent "$FOLLOWER_HOMEPAGE" | \
-            sed --regexp-extended --silent 's|.*ghcr.io/agoric/agoric-sdk:([0-9]+).*|\1|p'
-          )"
-
-          if test -z "$IMAGE_TAG"
-          then
-            echo "Couldn't extract image tag from '$FOLLOWER_HOMEPAGE'"
-            exit 1
-          fi
-
           if test "${{ steps.get-proposal-count-difference.outputs.DIFFERENCE }}" -gt "0"
           then
+            IMAGE_TAG="$(
+              curl --silent "$FOLLOWER_HOMEPAGE" | \
+              sed --regexp-extended --silent 's|.*ghcr.io/agoric/agoric-sdk:([0-9]+).*|\1|p'
+            )"
+
+            if test -z "$IMAGE_TAG"
+            then
+              echo "Couldn't extract image tag from '$FOLLOWER_HOMEPAGE'"
+              exit 1
+            fi
+
             gsutil rm \
               -a \
               -f \
